import 'dart:io';

import 'package:artisanal/args.dart';
import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

/// Creates an initial declarative native_prebuilt.yaml file.
class InitCommand extends Command<void> {
  InitCommand() {
    argParser.addOption(
      'output',
      abbr: 'o',
      defaultsTo: 'native_prebuilt.yaml',
      help: 'Path to the manifest to create.',
    );
    argParser.addOption('package', help: 'Dart package name.');
    argParser.addOption('asset-name', help: 'Code asset Dart library path.');
    argParser.addOption('library-stem', help: 'Native library stem.');
    argParser.addOption(
      'link-mode',
      allowed: ['dynamic_library', 'static_library'],
      defaultsTo: 'dynamic_library',
      help: 'Native payload/link mode.',
    );
    argParser.addOption(
      'release-repository',
      help: 'GitHub release repository in owner/repository form.',
    );
    argParser.addOption('release-tag', help: 'Initial release tag.');
    argParser.addOption(
      'source-repository',
      help: 'Git repository containing the native source.',
    );
    argParser.addOption(
      'source-revision',
      defaultsTo: 'main',
      help: 'Pinned source revision. Replace this with a commit SHA.',
    );
    argParser.addOption(
      'source-subdirectory',
      help: 'Optional buildable source subdirectory in the repository.',
    );
    argParser.addMultiOption(
      'platform',
      abbr: 'p',
      help: 'Artifact target (repeatable or comma-separated).',
    );
    argParser.addFlag('force', help: 'Overwrite an existing manifest.');
  }

  @override
  String get name => 'init';

  @override
  String get description =>
      'Generate an initial native_prebuilt.yaml scaffold.';

  @override
  Future<void> run() async {
    final outputPath = p.normalize(option('output') as String);
    final outputFile = File(outputPath).absolute;
    final force = (option('force') as bool?) ?? false;
    if (outputFile.existsSync() && !force) {
      throw UsageException(
        'Manifest already exists at ${outputFile.path}. Use --force to replace it.',
        usage,
      );
    }

    final pubspec = _readPubspec(outputFile.parent);
    final package =
        option('package') as String? ??
        pubspec['name'] as String? ??
        p.basename(outputFile.parent.path);
    final libraryStem =
        option('library-stem') as String? ?? package.replaceAll('-', '_');
    final assetName =
        option('asset-name') as String? ?? 'src/${libraryStem}_native.dart';
    final linkMode = option('link-mode') as String;
    final releaseRepository =
        option('release-repository') as String? ??
        _repositoryFromPubspec(pubspec) ??
        'OWNER/$package';
    final version = pubspec['version'] as String? ?? '0.1.0';
    final releaseTag = option('release-tag') as String? ?? '$package-v$version';
    final sourceRepository =
        option('source-repository') as String? ??
        _githubUrlFromRepository(releaseRepository);
    final sourceRevision = option('source-revision') as String;
    final sourceSubdirectory = option('source-subdirectory') as String?;
    final platforms = _platforms(option('platform') as List<String>?);

    outputFile.parent.createSync(recursive: true);
    outputFile.writeAsStringSync(
      renderInitialManifest(
        package: package,
        assetName: assetName,
        libraryStem: libraryStem,
        linkMode: linkMode,
        releaseRepository: releaseRepository,
        releaseTag: releaseTag,
        sourceRepository: sourceRepository,
        sourceRevision: sourceRevision,
        sourceSubdirectory: sourceSubdirectory,
        platforms: platforms,
      ),
    );
    io.info('Wrote ${outputFile.path}');
  }
}

/// Renders the initial YAML scaffold independently of the CLI command.
String renderInitialManifest({
  required String package,
  required String assetName,
  required String libraryStem,
  required String linkMode,
  required String releaseRepository,
  required String releaseTag,
  required String? sourceRepository,
  required String sourceRevision,
  required String? sourceSubdirectory,
  required List<String> platforms,
}) {
  final payload = linkMode == 'static_library'
      ? 'static_library'
      : 'dynamic_library';
  final buffer = StringBuffer()
    ..writeln('# Generated by: dart run native_prebuilt init')
    ..writeln('# Add declarative build.recipes before using the build hook.')
    ..writeln('schema: 1')
    ..writeln('package: ${_yamlScalar(package)}')
    ..writeln('asset_name: ${_yamlScalar(assetName)}')
    ..writeln('library_stem: ${_yamlScalar(libraryStem)}')
    ..writeln('link_mode: $linkMode')
    ..writeln()
    ..writeln('release:')
    ..writeln('  provider: github')
    ..writeln('  repository: ${_yamlScalar(releaseRepository)}')
    ..writeln('  tag: ${_yamlScalar(releaseTag)}');

  if (sourceRepository != null && sourceRepository.isNotEmpty) {
    buffer
      ..writeln()
      ..writeln('source:')
      ..writeln('  type: git')
      ..writeln('  repository: ${_yamlScalar(sourceRepository)}')
      ..writeln('  revision: ${_yamlScalar(sourceRevision)}');
    if (sourceSubdirectory != null && sourceSubdirectory.isNotEmpty) {
      buffer.writeln('  subdirectory: ${_yamlScalar(sourceSubdirectory)}');
    }
  }

  buffer
    ..writeln()
    ..writeln('artifacts:');
  for (final platform in platforms) {
    buffer
      ..writeln('  ${_yamlScalar(platform)}:')
      ..writeln('    archive: ${_yamlScalar('$libraryStem-$platform.tar.gz')}')
      ..writeln('    payload:')
      ..writeln('      type: $payload');
  }
  return buffer.toString();
}

Map<String, dynamic> _readPubspec(Directory directory) {
  final file = File(p.join(directory.path, 'pubspec.yaml'));
  if (!file.existsSync()) return const <String, dynamic>{};
  final document = loadYaml(file.readAsStringSync());
  if (document is! YamlMap) return const <String, dynamic>{};
  return {
    for (final entry in document.entries) entry.key.toString(): entry.value,
  };
}

String? _repositoryFromPubspec(Map<String, dynamic> pubspec) {
  final repository = pubspec['repository'];
  if (repository is String) {
    return _githubOwnerRepository(repository) ?? repository;
  }
  if (repository is Map) {
    final url = repository['url'];
    if (url is String) return _githubOwnerRepository(url) ?? url;
  }
  return null;
}

String? _githubUrlFromRepository(String repository) {
  final parts = repository.split('/');
  if (parts.length != 2 || parts.any((part) => part.isEmpty)) return null;
  return 'https://github.com/$repository';
}

String? _githubOwnerRepository(String url) {
  final uri = Uri.tryParse(url);
  if (uri == null || uri.host != 'github.com') return null;
  final parts = uri.pathSegments.where((part) => part.isNotEmpty).toList();
  if (parts.length < 2) return null;
  return '${parts[0]}/${parts[1].replaceFirst(RegExp(r'\.git$'), '')}';
}

List<String> _platforms(List<String>? values) {
  final requested = <String>[];
  for (final value in values ?? const <String>[]) {
    requested.addAll(value.split(',').map((item) => item.trim()));
  }
  final result = requested.where((item) => item.isNotEmpty).toSet().toList();
  return result.isEmpty ? ['linux-x64'] : result;
}

String _yamlScalar(String value) {
  if (RegExp(r'^[A-Za-z0-9_./+-]+$').hasMatch(value)) return value;
  return "'${value.replaceAll("'", "''")}'";
}
