import 'prebuilt_artifact.dart';
import 'release_source.dart';

/// A complete manifest of prebuilt native artifacts for a single package.
///
/// This is the central data structure that replaces the separate
/// `artifacts.dart` and `asset_hashes.dart` files. It contains everything
/// needed to download, verify, and install prebuilt binaries.
///
/// Instances should be declared as top-level `const` values, typically
/// generated by the `native_prebuilt manifest update` CLI command.
///
/// ```dart
/// const myPrebuilts = PrebuiltManifest(
///   schemaVersion: 1,
///   release: GitHubReleaseSource(
///     owner: 'myorg',
///     repository: 'myrepo',
///     tag: 'mylib-v1.0.0',
///   ),
///   // or GitLabReleaseSource(projectPath: 'mygroup/myrepo', tag: ...)
///   artifacts: {
///     'linux-x64': PrebuiltArtifact(
///       archiveName: 'mylib-linux-x64.tar.gz',
///       archiveSha256: '...',
///       payloadSha256: '...',
///       payload: DynamicLibraryPayload(libraryStem: 'mylib'),
///     ),
///   },
/// );
/// ```
final class PrebuiltManifest {
  const PrebuiltManifest({
    required this.schemaVersion,
    required this.release,
    required this.artifacts,
  });

  /// Schema version for forward compatibility.
  ///
  /// Currently `1`.
  final int schemaVersion;

  /// The release source from which artifacts are downloaded.
  final ReleaseSource release;

  /// Platform labels to artifact metadata.
  ///
  /// Keys are platform labels like `linux-x64`, `macos-arm64`,
  /// `ios-sim-arm64`, etc.
  final Map<String, PrebuiltArtifact> artifacts;

  /// Whether the given platform label has a prebuilt artifact.
  bool supports(String platformLabel) => artifacts.containsKey(platformLabel);

  /// Returns the artifact for [platformLabel], or `null` if not available.
  PrebuiltArtifact? operator [](String platformLabel) =>
      artifacts[platformLabel];

  Map<String, dynamic> toJson() => {
        'schema_version': schemaVersion,
        'release': release.toJson(),
        'artifacts': {
          for (final entry in artifacts.entries)
            entry.key: entry.value.toJson(),
        },
      };

  factory PrebuiltManifest.fromJson(Map<String, dynamic> json) {
    return PrebuiltManifest(
      schemaVersion: json['schema_version'] as int,
      release: ReleaseSource.fromJson(json['release'] as Map<String, dynamic>),
      artifacts: {
        for (final entry in (json['artifacts'] as Map<String, dynamic>).entries)
          entry.key: PrebuiltArtifact.fromJson(entry.value as Map<String, dynamic>),
      },
    );
  }
}
