import 'dart:io';

/// Generator tool for the generated_source fixture.
///
/// Reads a value from `input/value.txt` and generates a C source file
/// that returns that value.
void main(List<String> args) {
  if (args.length != 2) {
    print('Usage: generate.dart <input_dir> <output_file>');
    exit(1);
  }

  final inputDir = args[0];
  final outputPath = args[1];

  // Read the value from input/value.txt
  final valueFile = File('$inputDir/value.txt');
  if (!valueFile.existsSync()) {
    print('Error: ${valueFile.path} not found');
    exit(1);
  }

  final value = valueFile.readAsStringSync().trim();
  final intValue = int.tryParse(value);
  if (intValue == null) {
    print('Error: value.txt must contain an integer, got: $value');
    exit(1);
  }

  // Ensure output directory exists
  Directory(outputPath).parent.createSync(recursive: true);

  // Generate C source file
  final output = File(outputPath);
  output.writeAsStringSync('''
// Auto-generated by generate.dart — DO NOT EDIT.
#include "fixture.h"

static int s_value = $intValue;

FIXTURE_EXPORT int get_generated_value(void) {
  return s_value;
}
''');

  print('Generated: $outputPath (value=$intValue)');
}
